version: "3.8"

services:
  library-service:
    image: localhost:5000/library-service:${IMAGE_TAG:-latest}
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/library
      - SPRING_DATASOURCE_USERNAME=library
      - SPRING_DATASOURCE_PASSWORD=library
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data:
