version: '3.8'

services:
  books-api:
    image: odsoft
    build: .
    container_name: books-api
    ports:
      - "8081:8081"
    networks:
      - test-network
    restart: unless-stopped

  k6-odsoft:
    platform: "linux/amd64"
    image: grafana/k6:latest
    container_name: k6-odsoft
    volumes:
      - ./tests:/tests
    networks:
      - test-network
    entrypoint: ["tail", "-f", "/dev/null"] # Keeps the container running for executing tests
    depends_on:
      - books-api
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8g

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins   
    container_name: jenkins
    user: root
    environment:
      - TZ=Europe/Lisbon
    ports:
      - "8082:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - test-network
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000" 
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - test-network
    restart: unless-stopped

networks:
  test-network:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_extensions:
