spring:
  profiles: staging
  datasource:
    url: jdbc:postgresql://db:5432/library_staging
    username: library_staging
    password: staging_password
  jpa:
    hibernate:
      ddl-auto: validate  # verify schema matches
logging:
  level:
    root: INFO
